import bodyWave from "@/assets/wig-body-wave.jpg";
import bob from "@/assets/wig-bob.jpg";
import curly from "@/assets/wig-curly.jpg";
import blonde from "@/assets/wig-blonde.jpg";
import type { Customer, Order, Product, Task } from "./types";

export const CATEGORIES = [
  "Bob",
  "Straight",
  "Curly",
  "Body Wave",
  "Deep Wave",
  "Lace Wig",
  "Glueless Wig",
  "Colored Wig",
  "Long Wig",
  "Short Wig",
  "New Arrivals",
  "Best Sellers",
];

export const TEXTURES = ["Straight", "Body Wave", "Deep Wave", "Curly", "Kinky Straight"];
export const COLORS = ["Natural Black", "Dark Brown", "Chestnut", "Honey Blonde", "Burgundy"];

const care =
  "Wash every 8-10 wears with a sulphate-free shampoo in lukewarm water. Detangle from the ends upward with a wide-tooth comb. Air dry on a wig stand. Use heat tools below 160°C and always apply a heat protectant — human-blend fibre is heat friendly but not heat proof.";
const shipping =
  "Dispatched within 1-2 business days. Nationwide courier delivery in 2-4 business days. Free delivery on orders over R2 500. Tracking number shared by email on dispatch.";
const returns =
  "14-day returns on unworn, unwashed wigs in original packaging with the lace uncut. Exchanges for length or colour are free once per order. Custom-coloured units are final sale.";

function p(x: Product): Product {
  return x;
}

export const PRODUCTS: Product[] = [
  p({
    id: "wig-001",
    name: "Amara Body Wave Human-Blend Wig",
    sku: "ZD-BW-2201",
    price: 3450,
    salePrice: 2990,
    image: bodyWave,
    categories: ["Body Wave", "Lace Wig", "Long Wig", "Best Sellers"],
    composition: "60% human hair / 40% premium heat-friendly fibre (human-blend)",
    length: 22,
    texture: "Body Wave",
    color: "Natural Black",
    density: "180%",
    cap: "13x4 HD lace frontal, adjustable straps, 4 combs",
    quantity: 14,
    description:
      "Our signature human-blend body wave with a soft, bouncy movement that holds its pattern between washes. The HD lace frontal melts against a wide range of skin tones for a natural hairline.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.8,
    sold: 128,
  }),
  p({
    id: "wig-002",
    name: "Zola Sleek Bob Human-Blend Wig",
    sku: "ZD-BOB-1002",
    price: 2150,
    image: bob,
    categories: ["Bob", "Straight", "Short Wig", "Best Sellers", "Glueless Wig"],
    composition: "55% human hair / 45% premium fibre (human-blend)",
    length: 10,
    texture: "Straight",
    color: "Natural Black",
    density: "150%",
    cap: "Glueless 4x4 closure with elastic band",
    quantity: 6,
    description:
      "A precision-cut blunt bob that stays sleek all day. Glueless construction means it goes on in under two minutes — ideal for a first wig or a fast weekday look.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.9,
    sold: 164,
  }),
  p({
    id: "wig-003",
    name: "Naledi Deep Curl Human-Blend Wig",
    sku: "ZD-CRL-3310",
    price: 3890,
    image: curly,
    categories: ["Curly", "Deep Wave", "Lace Wig", "New Arrivals"],
    composition: "60% human hair / 40% premium fibre (human-blend)",
    length: 18,
    texture: "Curly",
    color: "Natural Black",
    density: "200%",
    cap: "13x6 lace frontal, pre-plucked hairline",
    quantity: 9,
    description:
      "Full, defined curls with generous 200% density. Refresh with water and a leave-in to bring the curl pattern straight back.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.7,
    sold: 73,
  }),
  p({
    id: "wig-004",
    name: "Thandi Honey Blonde Straight Human-Blend Wig",
    sku: "ZD-STR-4420",
    price: 4250,
    salePrice: 3790,
    image: blonde,
    categories: ["Straight", "Colored Wig", "Long Wig", "New Arrivals"],
    composition: "55% human hair / 45% premium fibre (human-blend)",
    length: 26,
    texture: "Straight",
    color: "Honey Blonde",
    density: "180%",
    cap: "13x4 lace front with bleached knots",
    quantity: 3,
    description:
      "A warm honey blonde with subtle root shadowing for depth. Pre-toned in studio so no additional colour work is required.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.6,
    sold: 41,
  }),
  p({
    id: "wig-005",
    name: "Lerato Chestnut Body Wave Human-Blend Wig",
    sku: "ZD-BW-2208",
    price: 3650,
    image: bodyWave,
    categories: ["Body Wave", "Colored Wig", "Long Wig"],
    composition: "60% human hair / 40% premium fibre (human-blend)",
    length: 24,
    texture: "Body Wave",
    color: "Chestnut",
    density: "180%",
    cap: "13x4 lace frontal, adjustable straps",
    quantity: 11,
    description:
      "A soft chestnut body wave that reads warm in daylight and rich indoors. A gentle way into colour without going light.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.7,
    sold: 58,
  }),
  p({
    id: "wig-006",
    name: "Sindi Glueless Curly Bob Human-Blend Wig",
    sku: "ZD-BOB-1015",
    price: 2450,
    image: curly,
    categories: ["Bob", "Curly", "Glueless Wig", "Short Wig", "New Arrivals"],
    composition: "55% human hair / 45% premium fibre (human-blend)",
    length: 12,
    texture: "Curly",
    color: "Dark Brown",
    density: "160%",
    cap: "Glueless wear-and-go, breathable cap",
    quantity: 2,
    description:
      "A playful curly bob on a wear-and-go cap. Light enough for daily wear and forgiving on humid days.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.8,
    sold: 96,
  }),
  p({
    id: "wig-007",
    name: "Buhle Kinky Straight Human-Blend Wig",
    sku: "ZD-STR-4408",
    price: 3150,
    image: bob,
    categories: ["Straight", "Lace Wig", "Long Wig"],
    composition: "60% human hair / 40% premium fibre (human-blend)",
    length: 20,
    texture: "Kinky Straight",
    color: "Natural Black",
    density: "170%",
    cap: "5x5 HD lace closure",
    quantity: 0,
    description:
      "A blown-out kinky straight texture that blends beautifully with natural leave-out for an everyday look.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.5,
    sold: 34,
  }),
  p({
    id: "wig-008",
    name: "Ayanda Burgundy Deep Wave Human-Blend Wig",
    sku: "ZD-DW-5501",
    price: 4050,
    image: curly,
    categories: ["Deep Wave", "Colored Wig", "Lace Wig", "Long Wig"],
    composition: "60% human hair / 40% premium fibre (human-blend)",
    length: 22,
    texture: "Deep Wave",
    color: "Burgundy",
    density: "190%",
    cap: "13x4 lace frontal",
    quantity: 5,
    description:
      "A deep wave in a rich burgundy that catches light without reading loud. A statement unit for events.",
    care,
    shipping,
    returns,
    status: "active",
    rating: 4.6,
    sold: 27,
  }),
];

export const CUSTOMERS: Customer[] = [
  {
    id: "cus-001",
    name: "Nomsa Dlamini",
    email: "nomsa.dlamini@example.com",
    phone: "+27 82 441 0091",
    city: "Johannesburg",
    tier: "vip",
    joined: "2025-02-14",
    orders: 7,
    spent: 24150,
    notes: "Prefers 22\" body wave, 180% density. Sensitive scalp — glueless preferred.",
  },
  {
    id: "cus-002",
    name: "Lebo Mokoena",
    email: "lebo.mokoena@example.com",
    phone: "+27 71 220 8834",
    city: "Pretoria",
    tier: "existing",
    joined: "2025-06-02",
    orders: 3,
    spent: 8340,
    notes: "Bought two bobs. Interested in a coloured unit for December.",
  },
  {
    id: "cus-003",
    name: "Aisha Patel",
    email: "aisha.patel@example.com",
    phone: "+27 83 907 1122",
    city: "Durban",
    tier: "existing",
    joined: "2025-04-19",
    orders: 4,
    spent: 12980,
    notes: "Always asks about care routine. Send care guide with each order.",
  },
  {
    id: "cus-004",
    name: "Chantal Adams",
    email: "chantal.adams@example.com",
    phone: "+27 84 552 7710",
    city: "Cape Town",
    tier: "new",
    joined: "2026-08-21",
    orders: 1,
    spent: 2150,
    notes: "First-time wig wearer. Booked a virtual consultation.",
  },
  {
    id: "cus-005",
    name: "Zanele Khumalo",
    email: "zanele.khumalo@example.com",
    phone: "+27 79 118 4432",
    city: "Soweto",
    tier: "vip",
    joined: "2024-11-08",
    orders: 11,
    spent: 38720,
    notes: "Bridal client. Referred four customers.",
  },
  {
    id: "cus-006",
    name: "Mpho Sithole",
    email: "mpho.sithole@example.com",
    phone: "+27 76 330 2214",
    city: "Bloemfontein",
    tier: "new",
    joined: "2026-08-30",
    orders: 1,
    spent: 3450,
    notes: "Found us through Instagram reel.",
  },
];

export const ORDERS: Order[] = [
  {
    id: "ZD-1047",
    customerId: "cus-001",
    customerName: "Nomsa Dlamini",
    email: "nomsa.dlamini@example.com",
    date: "2026-09-02",
    status: "pending",
    items: [{ productId: "wig-001", name: "Amara Body Wave Human-Blend Wig", qty: 1, price: 2990 }],
    total: 2990,
    address: "18 Oak Avenue, Sandton, Johannesburg",
  },
  {
    id: "ZD-1046",
    customerId: "cus-004",
    customerName: "Chantal Adams",
    email: "chantal.adams@example.com",
    date: "2026-09-01",
    status: "processing",
    items: [{ productId: "wig-002", name: "Zola Sleek Bob Human-Blend Wig", qty: 1, price: 2150 }],
    total: 2150,
    address: "7 Kloof Street, Gardens, Cape Town",
  },
  {
    id: "ZD-1045",
    customerId: "cus-005",
    customerName: "Zanele Khumalo",
    email: "zanele.khumalo@example.com",
    date: "2026-08-29",
    status: "shipped",
    items: [
      { productId: "wig-004", name: "Thandi Honey Blonde Straight Human-Blend Wig", qty: 1, price: 3790 },
      { productId: "wig-002", name: "Zola Sleek Bob Human-Blend Wig", qty: 1, price: 2150 },
    ],
    total: 5940,
    address: "45 Vilakazi Street, Orlando West, Soweto",
  },
  {
    id: "ZD-1044",
    customerId: "cus-003",
    customerName: "Aisha Patel",
    email: "aisha.patel@example.com",
    date: "2026-08-24",
    status: "delivered",
    items: [{ productId: "wig-003", name: "Naledi Deep Curl Human-Blend Wig", qty: 1, price: 3890 }],
    total: 3890,
    address: "22 Ridge Road, Morningside, Durban",
  },
  {
    id: "ZD-1043",
    customerId: "cus-002",
    customerName: "Lebo Mokoena",
    email: "lebo.mokoena@example.com",
    date: "2026-08-18",
    status: "delivered",
    items: [{ productId: "wig-006", name: "Sindi Glueless Curly Bob Human-Blend Wig", qty: 2, price: 2450 }],
    total: 4900,
    address: "9 Church Street, Hatfield, Pretoria",
  },
  {
    id: "ZD-1042",
    customerId: "cus-006",
    customerName: "Mpho Sithole",
    email: "mpho.sithole@example.com",
    date: "2026-08-12",
    status: "cancelled",
    items: [{ productId: "wig-005", name: "Lerato Chestnut Body Wave Human-Blend Wig", qty: 1, price: 3650 }],
    total: 3650,
    address: "3 Nelson Mandela Drive, Bloemfontein",
  },
];

export const TASKS: Task[] = [
  {
    id: "task-001",
    name: "Photograph the new glueless bob range",
    description: "Studio shoot for three new glueless units, front, side and back angles.",
    priority: "high",
    assignee: "Thabo",
    duration: "1 day",
    deadline: "2026-09-08",
    dependencies: "",
    status: "in_progress",
    source: "manual",
  },
  {
    id: "task-002",
    name: "Restock 22\" body wave units",
    description: "Place supplier order for 20 units before the festive rush.",
    priority: "urgent",
    assignee: "Zandile",
    duration: "2 hours",
    deadline: "2026-09-05",
    dependencies: "",
    status: "todo",
    source: "manual",
  },
  {
    id: "task-003",
    name: "Follow up with consultation clients",
    description: "Call the four clients from last week's consultations.",
    priority: "medium",
    assignee: "Nandi",
    duration: "3 hours",
    deadline: "2026-09-06",
    dependencies: "",
    status: "todo",
    source: "manual",
  },
  {
    id: "task-004",
    name: "Publish September care guide",
    description: "Email the seasonal human-blend care guide to existing customers.",
    priority: "low",
    assignee: "Nandi",
    duration: "4 hours",
    deadline: "2026-09-15",
    dependencies: "Photograph the new glueless bob range",
    status: "completed",
    source: "manual",
  },
];

export const REVENUE_SERIES = [
  { month: "Mar", revenue: 48200, orders: 18, customers: 42 },
  { month: "Apr", revenue: 52700, orders: 21, customers: 51 },
  { month: "May", revenue: 61400, orders: 24, customers: 63 },
  { month: "Jun", revenue: 58900, orders: 22, customers: 71 },
  { month: "Jul", revenue: 74300, orders: 29, customers: 86 },
  { month: "Aug", revenue: 91500, orders: 36, customers: 104 },
];

export function currency(v: number) {
  return "R " + v.toLocaleString("en-ZA", { maximumFractionDigits: 0 });
}
